# Context-based action probability modifiers
high_activity:
  like: 1.3
  reply: 1.2
  tweet: 0.8

low_activity:
  tweet: 1.4
  like: 0.8
  reply: 0.9

positive_sentiment:
  like: 1.2
  retweet: 1.1
  reply: 1.1

negative_sentiment:
  reply: 1.3
  tweet: 0.9
  like: 0.8

trending_topics:
  tweet: 1.2
  retweet: 1.5
  reply: 1.1
