version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: trenches
      POSTGRES_USER: trenches
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5.14
    environment:
      NEO4J_AUTH: neo4j/verysecret123
    ports:
      - "7474:7474"
      - "7687:7687"
  
  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: trenches
      DB_PASSWORD: secret
      DB_NAME: trenches

volumes:
  pgdata:
  grafana_data: